### ISSUE TITLE
let biomes have there biome specific blocks

### ISSUE THREAD

**Issue by MimzyFang** [ly-nxs/aerolith#4]
biomes should have biome specific blocks like sand in deserts

right now they just have grass
some examples:
![2024-07-21_10 44 14](https://github.com/user-attachments/assets/a8945e6a-7756-4309-84f9-d7d000a9e7cc)
![2024-07-21_10 52 10](https://github.com/user-attachments/assets/6562ad24-f7e7-4c48-8fe0-68d9e2a34ca1)

**Comment by ly-nxs** [comment]
Which version of the datapack are you using?

**Comment by ly-nxs** [comment]
Ok I fixed it, download the new version 1.3.2

**Comment by MimzyFang** [comment]
> Ok I fixed it, download the new version 1.3.2

yep I just tried it and it works with vanilla biomes 
still had some issues when I tested it against a modpack with BOP where it did not work with bop biomes though I am unshure how much you could do about this so I am closing

in case you want to fix it with mods feel free to reopen the issue

**Comment by ly-nxs** [comment]
I don't know any further changes I could make, are the BoP trees and stuff
working or nothing?

**Comment by MimzyFang** [comment]
The trees are working just biomes that have other blocks then grass as its floor don't have the right blocks but grass instead

**Comment by clpie26** [comment]
Does it work with 1.3.0?
